name: SEO Curve Workflow

on: [push]  # Trigger the workflow on push events

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout the code
      - run: echo Hello, world!  # Print a message
